import { Formation, Player } from './types';

export const FORMATIONS: Formation[] = [
  {
    id: '4-3-3',
    name: '4-3-3 (Clássico)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'DE', role: 'Lateral Esquerdo', shortRole: 'DE', x: 15, y: 72 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 38, y: 75 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 62, y: 75 },
      { id: 'DD', role: 'Lateral Direito', shortRole: 'DD', x: 85, y: 72 },
      { id: 'MDF', role: 'Médio Defensivo', shortRole: 'MDF', x: 50, y: 55 },
      { id: 'MC_E', role: 'Médio Interior Esquerdo', shortRole: 'MCE', x: 32, y: 42 },
      { id: 'MC_D', role: 'Médio Interior Direito', shortRole: 'MCD', x: 68, y: 42 },
      { id: 'EE', role: 'Extremo Esquerdo', shortRole: 'EE', x: 20, y: 20 },
      { id: 'PL', role: 'Ponta de Lança', shortRole: 'PL', x: 50, y: 12 },
      { id: 'ED', role: 'Extremo Direito', shortRole: 'ED', x: 80, y: 20 },
    ],
  },
  {
    id: '4-4-2',
    name: '4-4-2 (Duas Linhas)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'DE', role: 'Lateral Esquerdo', shortRole: 'DE', x: 15, y: 72 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 38, y: 75 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 62, y: 75 },
      { id: 'DD', role: 'Lateral Direito', shortRole: 'DD', x: 85, y: 72 },
      { id: 'MD_E', role: 'Médio Ala Esquerdo', shortRole: 'ME', x: 15, y: 44 },
      { id: 'MC_E', role: 'Médio Centro Esquerdo', shortRole: 'MCE', x: 38, y: 48 },
      { id: 'MC_D', role: 'Médio Centro Direito', shortRole: 'MCD', x: 62, y: 48 },
      { id: 'MD_D', role: 'Médio Ala Direito', shortRole: 'MD', x: 85, y: 44 },
      { id: 'PL_E', role: 'Ponta de Lança Esquerdo', shortRole: 'PLE', x: 35, y: 16 },
      { id: 'PL_D', role: 'Ponta de Lança Direito', shortRole: 'PLD', x: 65, y: 16 },
    ],
  },
  {
    id: '3-5-2',
    name: '3-5-2 (Dominância Central)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 28, y: 74 },
      { id: 'CC', role: 'Defesa Central', shortRole: 'CC', x: 50, y: 77 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 72, y: 74 },
      { id: 'ALA_E', role: 'Ala Esquerdo', shortRole: 'ALE', x: 12, y: 50 },
      { id: 'ALA_D', role: 'Ala Direito', shortRole: 'ALD', x: 88, y: 50 },
      { id: 'MDF_E', role: 'Médio Recuado Esquerdo', shortRole: 'MRE', x: 32, y: 46 },
      { id: 'MDF_D', role: 'Médio Recuado Direito', shortRole: 'MRD', x: 68, y: 46 },
      { id: 'MO', role: 'Médio Ofensivo', shortRole: 'MO', x: 50, y: 30 },
      { id: 'PL_E', role: 'Avançado Esquerdo', shortRole: 'AE', x: 35, y: 15 },
      { id: 'PL_D', role: 'Avançado Direito', shortRole: 'AD', x: 65, y: 15 },
    ],
  },
  {
    id: '3-4-3',
    name: '3-4-3 (Ofensivo Dinâmico)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 28, y: 74 },
      { id: 'CC', role: 'Defesa Central', shortRole: 'CC', x: 50, y: 77 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 72, y: 74 },
      { id: 'ALA_E', role: 'Ala Esquerdo', shortRole: 'ALE', x: 12, y: 48 },
      { id: 'MC_E', role: 'Médio Centro Esquerdo', shortRole: 'MCE', x: 35, y: 48 },
      { id: 'MC_D', role: 'Médio Centro Direito', shortRole: 'MCD', x: 65, y: 48 },
      { id: 'ALA_D', role: 'Ala Direito', shortRole: 'ALD', x: 88, y: 48 },
      { id: 'EE', role: 'Avançado Esquerdo / Extremo', shortRole: 'EE', x: 20, y: 20 },
      { id: 'PL', role: 'Ponta de Lança', shortRole: 'PL', x: 50, y: 12 },
      { id: 'ED', role: 'Avançado Direito / Extremo', shortRole: 'ED', x: 80, y: 20 },
    ],
  },
  {
    id: '4-2-3-1',
    name: '4-2-3-1 (Equilíbrio Moderno)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'DE', role: 'Lateral Esquerdo', shortRole: 'DE', x: 15, y: 72 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 38, y: 75 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 62, y: 75 },
      { id: 'DD', role: 'Lateral Direito', shortRole: 'DD', x: 85, y: 72 },
      { id: 'MDF_E', role: 'Médio Defensivo Esquerdo', shortRole: 'MDE', x: 35, y: 55 },
      { id: 'MDF_D', role: 'Médio Defensivo Direito', shortRole: 'MDD', x: 65, y: 55 },
      { id: 'MCO_E', role: 'Ala/Extremo Esquerdo', shortRole: 'EE', x: 18, y: 32 },
      { id: 'MCO_C', role: 'Médio Ofensivo Centro', shortRole: 'MCO', x: 50, y: 32 },
      { id: 'MCO_D', role: 'Ala/Extremo Direito', shortRole: 'ED', x: 82, y: 32 },
      { id: 'PL', role: 'Ponta de Lança', shortRole: 'PL', x: 50, y: 12 },
    ],
  },
  {
    id: '4-1-3-2',
    name: '4-1-3-2 (Ataque Apoiado)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'DE', role: 'Lateral Esquerdo', shortRole: 'DE', x: 15, y: 72 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 38, y: 75 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 62, y: 75 },
      { id: 'DD', role: 'Lateral Direito', shortRole: 'DD', x: 85, y: 72 },
      { id: 'MDF', role: 'Médio Defensivo', shortRole: 'MDF', x: 50, y: 56 },
      { id: 'ME', role: 'Médio Esquerdo', shortRole: 'ME', x: 20, y: 38 },
      { id: 'MC', role: 'Médio Centro', shortRole: 'MC', x: 50, y: 38 },
      { id: 'MD', role: 'Médio Direito', shortRole: 'MD', x: 80, y: 38 },
      { id: 'PL_E', role: 'Ponta de Lança Esquerdo', shortRole: 'PLE', x: 35, y: 16 },
      { id: 'PL_D', role: 'Ponta de Lança Direito', shortRole: 'PLD', x: 65, y: 16 },
    ],
  },
  {
    id: '4-1-2-1-2',
    name: '4-4-2 (Losango / Diamond)',
    positions: [
      { id: 'GR', role: 'Guarda-Redes', shortRole: 'GR', x: 50, y: 88 },
      { id: 'DE', role: 'Lateral Esquerdo', shortRole: 'DE', x: 15, y: 72 },
      { id: 'CE', role: 'Central Esquerdo', shortRole: 'CE', x: 38, y: 75 },
      { id: 'CD', role: 'Central Direito', shortRole: 'CD', x: 62, y: 75 },
      { id: 'DD', role: 'Lateral Direito', shortRole: 'DD', x: 85, y: 72 },
      { id: 'MDF', role: 'Médio Defensivo', shortRole: 'MDF', x: 50, y: 58 },
      { id: 'MCE', role: 'Médio Centro Esquerdo', shortRole: 'MCE', x: 28, y: 44 },
      { id: 'MCD', role: 'Médio Centro Direito', shortRole: 'MCD', x: 72, y: 44 },
      { id: 'MO', role: 'Médio Ofensivo', shortRole: 'MO', x: 50, y: 30 },
      { id: 'PL_E', role: 'Ponta de Lança Esquerdo', shortRole: 'PLE', x: 35, y: 16 },
      { id: 'PL_D', role: 'Ponta de Lança Direito', shortRole: 'PLD', x: 65, y: 16 },
    ],
  },
];

export const INITIAL_PLAYERS: Player[] = [
  // Guarda-redes
  {
    id: 'p1',
    name: 'Diogo Costa',
    number: 99,
    positionGroup: 'GK',
    position: 'GR',
    preferredFoot: 'Direito',
    status: 'Titular',
    rating: 5,
    notes: 'Excelente no um contra um, jogo de rins e saída rápida de bola longa guiando ataques.',
    birthDate: '1999-09-19',
  },
  {
    id: 'p2',
    name: 'Ricardo Velho',
    number: 1,
    positionGroup: 'GK',
    position: 'GR',
    preferredFoot: 'Direito',
    status: 'Suplente',
    rating: 4,
    notes: 'Seguro nas bolas aéreas e bom controlo da linha defensiva nas bolas paradas.',
    birthDate: '1998-08-20',
  },
  // Defesas
  {
    id: 'p3',
    name: 'António Silva',
    number: 4,
    positionGroup: 'DEF',
    position: 'DC',
    preferredFoot: 'Direito',
    status: 'Titular',
    rating: 5,
    notes: 'Excelente na antecipação e rápido na recuperação. Jovem com margem de progressão.',
    birthDate: '2008-10-31',
  },
  {
    id: 'p4',
    name: 'Gonçalo Inácio',
    number: 3,
    positionGroup: 'DEF',
    position: 'DC',
    preferredFoot: 'Esquerdo',
    status: 'Titular',
    rating: 5,
    notes: 'Canhoto que assegura uma excelente saída de bola em progressão. Pode atuar à esquerda.',
    birthDate: '2009-08-25',
  },
  {
    id: 'p5',
    name: 'Diogo Leite',
    number: 15,
    positionGroup: 'DEF',
    position: 'DC',
    preferredFoot: 'Esquerdo',
    status: 'Suplente',
    rating: 4,
    notes: 'Central sólido, forte no desarme aéreo e posicionamento em bloco baixo.',
    birthDate: '2009-01-23',
  },
  {
    id: 'p6',
    name: 'Nuno Mendes',
    number: 19,
    positionGroup: 'DEF',
    position: 'DE',
    preferredFoot: 'Esquerdo',
    status: 'Titular',
    rating: 5,
    notes: 'Lateral explosivo. Excelente no apoio ao ataque e cruzamento tenso.',
    birthDate: '2002-06-19',
  },
  {
    id: 'p7',
    name: 'João Cancelo',
    number: 2,
    positionGroup: 'DEF',
    position: 'DD',
    preferredFoot: 'Ambos',
    status: 'Titular',
    rating: 5,
    notes: 'Extremamente versátil, joga nas duas alas por dentro como médio organizador.',
    birthDate: '2008-05-27',
  },
  {
    id: 'p8',
    name: 'Diogo Dalot',
    number: 22,
    positionGroup: 'DEF',
    position: 'DD',
    preferredFoot: 'Direito',
    status: 'Suplente',
    rating: 4,
    notes: 'Defensivamente robusto e com bom timing de sobreposição no corredor direito.',
  },
  // Médios
  {
    id: 'p9',
    name: 'João Neves',
    number: 87,
    positionGroup: 'MID',
    position: 'MDF',
    preferredFoot: 'Direito',
    status: 'Titular',
    rating: 5,
    notes: 'Incansável na pressão. Grande capacidade de passe curto e transporte sob forte pressão.',
  },
  {
    id: 'p10',
    name: 'Vitinha Ferreira',
    number: 10,
    positionGroup: 'MID',
    position: 'MC',
    preferredFoot: 'Direito',
    status: 'Titular',
    rating: 5,
    notes: 'O motor e cérebro da equipa. Ritmo de passe magistral e excelente finta curta.',
  },
  {
    id: 'p11',
    name: 'Otávio Monteiro',
    number: 25,
    positionGroup: 'MID',
    position: 'MCO',
    preferredFoot: 'Direito',
    status: 'Suplente',
    rating: 4,
    notes: 'Proporciona agressividade defensiva no meio-campo e polivalência como extremo-interior.',
  },
  {
    id: 'p12',
    name: 'Mateus Fernandes',
    number: 18,
    positionGroup: 'MID',
    position: 'MC',
    preferredFoot: 'Direito',
    status: 'Reservado',
    rating: 3,
    notes: 'Jovem promessa. Boa chegada à área, versátil em sistemas de duplo pivot.',
  },
  {
    id: 'p13',
    name: 'Daniel Bragança',
    number: 6,
    positionGroup: 'MID',
    position: 'MC',
    preferredFoot: 'Esquerdo',
    status: 'Suplente',
    rating: 4,
    notes: 'Visão de jogo refinada e excelente pé esquerdo para desbloquear blocos baixos.',
  },
  // Avançados
  {
    id: 'p14',
    name: 'Rafael Leão',
    number: 17,
    positionGroup: 'ATT',
    position: 'EE',
    preferredFoot: 'Esquerdo',
    status: 'Titular',
    rating: 5,
    notes: 'Imparável em velocidade e no um-para-um. Define rumos contra defesas subidas.',
  },
  {
    id: 'p15',
    name: 'Diogo Jota',
    number: 11,
    positionGroup: 'ATT',
    position: 'PL',
    preferredFoot: 'Ambos',
    status: 'Suplente',
    rating: 5,
    notes: 'Instinto matador extraordinário na grande área. Excelente jogo de cabeça apesar da estatura.',
  },
  {
    id: 'p16',
    name: 'Francisco Conceição',
    number: 26,
    positionGroup: 'ATT',
    position: 'ED',
    preferredFoot: 'Esquerdo',
    status: 'Suplente',
    rating: 4,
    notes: 'Extremo puro de pé trocado. Agitador de jogo elétrico no corredor lateral.',
  },
  {
    id: 'p17',
    name: 'Gonçalo Ramos',
    number: 9,
    positionGroup: 'ATT',
    position: 'PL',
    preferredFoot: 'Direito',
    status: 'Titular',
    rating: 4,
    notes: 'Excelente primeiro defensor na frente de ataque. Movimentos inteligentes nos apoios.',
  },
  {
    id: 'p18',
    name: 'Trincão Silva',
    number: 14,
    positionGroup: 'ATT',
    position: 'ED',
    preferredFoot: 'Esquerdo',
    status: 'Reservado',
    rating: 4,
    notes: 'Forte na condução criativa no corredor central e no remate em arco.',
  },
];
